#!/usr/bin/env bash
set -euo pipefail

OUT="${1:-library.luau}"

python3 - <<'PY'
from pathlib import Path

def read(p):
    return Path(p).read_text()

theme = read('src/core/theme.luau')
utils = read('src/core/utils.luau')
sidebar = read('src/components/sidebar.luau')
topbar = read('src/components/topbar.luau')
dashboard = read('src/components/dashboard.luau')
init = read('src/init.luau')

# strip requires from module files and keep bodies
import re

def strip_module(code):
    code = re.sub(r'^local\s+Theme\s*=\s*require\([^\n]+\)\n?', '', code, flags=re.M)
    code = re.sub(r'^local\s+Utils\s*=\s*require\([^\n]+\)\n?', '', code, flags=re.M)
    code = re.sub(r'^local\s+Sidebar\s*=\s*require\([^\n]+\)\n?', '', code, flags=re.M)
    code = re.sub(r'^local\s+Topbar\s*=\s*require\([^\n]+\)\n?', '', code, flags=re.M)
    code = re.sub(r'^local\s+Dashboard\s*=\s*require\([^\n]+\)\n?', '', code, flags=re.M)
    return code.strip()

def strip_init(code):
    code = re.sub(r'^local\s+Theme\s*=\s*require\([^\n]+\)\n?', 'local Theme = __modules.theme\n', code, flags=re.M)
    code = re.sub(r'^local\s+Utils\s*=\s*require\([^\n]+\)\n?', 'local Utils = __modules.utils\n', code, flags=re.M)
    code = re.sub(r'^local\s+Sidebar\s*=\s*require\([^\n]+\)\n?', 'local Sidebar = __modules.sidebar\n', code, flags=re.M)
    code = re.sub(r'^local\s+Topbar\s*=\s*require\([^\n]+\)\n?', 'local Topbar = __modules.topbar\n', code, flags=re.M)
    code = re.sub(r'^local\s+Dashboard\s*=\s*require\([^\n]+\)\n?', 'local Dashboard = __modules.dashboard\n', code, flags=re.M)
    return code.strip()

bundle = f'''--[[
	Worst-UI-Library (Open-source bundled build)
	Generated by ./build.sh
	This file is self-contained (NO external require needed).
]]

local __modules = {{}}

__modules.theme = (function()
{theme.strip()}
end)()

__modules.utils = (function()
{utils.strip()}
end)()

__modules.sidebar = (function()
	local Theme = __modules.theme
	local Utils = __modules.utils
{strip_module(sidebar)}
end)()

__modules.topbar = (function()
	local Theme = __modules.theme
	local Utils = __modules.utils
{strip_module(topbar)}
end)()

__modules.dashboard = (function()
	local Theme = __modules.theme
	local Utils = __modules.utils
{strip_module(dashboard)}
end)()

return (function()
{strip_init(init)}
end)()
'''
Path('library.luau').write_text(bundle)
PY

if command -v darklua >/dev/null 2>&1; then
  darklua process library.luau main.lua --format dense
else
  cp library.luau main.lua
fi

if [[ "$OUT" == "main.lua" ]]; then
  cp main.lua "$OUT"
fi

echo "Build done: library.luau (readable, standalone) + main.lua (minified)"
