--[[
	Worst-UI-Library (Open-source bundled build)
	Generated by ./build.sh
	This file is self-contained (NO external require needed).
]]

local __modules = {}

__modules.theme = (function()
local Theme = {}

Theme.Colors = {
	Background = Color3.fromRGB(6, 10, 18),
	Panel = Color3.fromRGB(10, 14, 24),
	PanelSecondary = Color3.fromRGB(13, 18, 30),
	TextPrimary = Color3.fromRGB(244, 247, 255),
	TextSecondary = Color3.fromRGB(151, 160, 178),
	Accent = Color3.fromRGB(255, 33, 43),
	AccentSoft = Color3.fromRGB(73, 19, 24),
	Stroke = Color3.fromRGB(35, 43, 60),
}

Theme.Corner = {
	Small = UDim.new(0, 8),
	Medium = UDim.new(0, 12),
	Large = UDim.new(0, 16),
}

return Theme
end)()

__modules.utils = (function()
local Utils = {}

function Utils.Create(className, props)
	local instance = Instance.new(className)
	if props then
		for key, value in pairs(props) do
			pcall(function()
				instance[key] = value
			end)
		end
	end
	return instance
end

function Utils.ApplyCorner(instance, radius)
	local corner = Instance.new("UICorner")
	corner.CornerRadius = radius
	corner.Parent = instance
	return corner
end

function Utils.ApplyStroke(instance, color, transparency)
	local stroke = Instance.new("UIStroke")
	stroke.Color = color
	stroke.Transparency = transparency or 0.4
	stroke.Thickness = 1
	stroke.Parent = instance
	return stroke
end

function Utils.GetGuiParent()
	local success, result = pcall(function()
		if gethui then
			return gethui()
		end
		if syn and syn.protect_gui then
			local gui = Instance.new("ScreenGui")
			syn.protect_gui(gui)
			gui.Parent = game:GetService("CoreGui")
			return gui
		end
		return game:GetService("CoreGui")
	end)

	if success and result then
		return result
	end

	local players = game:GetService("Players")
	local localPlayer = players.LocalPlayer
	if localPlayer then
		return localPlayer:WaitForChild("PlayerGui")
	end

	return game:GetService("CoreGui")
end

return Utils
end)()

__modules.sidebar = (function()
	local Theme = __modules.theme
	local Utils = __modules.utils
local Sidebar = {}

local ITEMS = {"Dashboard", "Player", "Visuals", "World", "Combat", "Miscellaneous", "Settings"}

function Sidebar.Create(parent)
	local sidebar = Utils.Create("Frame", {
		Name = "Sidebar",
		BackgroundColor3 = Theme.Colors.Panel,
		BorderSizePixel = 0,
		Size = UDim2.new(0, 290, 1, -20),
		Position = UDim2.fromOffset(0, 10),
		Parent = parent,
	})
	Utils.ApplyCorner(sidebar, Theme.Corner.Medium)
	Utils.ApplyStroke(sidebar, Theme.Colors.Stroke, 0.5)

	local header = Utils.Create("TextLabel", {BackgroundTransparency = 1, Text = "☠ TitanUI", TextColor3 = Theme.Colors.TextPrimary, TextSize = 34, Font = Enum.Font.GothamBold, Size = UDim2.new(1, -20, 0, 70), Position = UDim2.fromOffset(14, 8), TextXAlignment = Enum.TextXAlignment.Left, Parent = sidebar})

	for index, label in ipairs(ITEMS) do
		local y = 88 + ((index - 1) * 76)
		local button = Utils.Create("TextButton", {
			Name = label,
			AutoButtonColor = false,
			BackgroundColor3 = index == 1 and Theme.Colors.Accent or Theme.Colors.Panel,
			BackgroundTransparency = index == 1 and 0 or 1,
			TextColor3 = Theme.Colors.TextPrimary,
			TextXAlignment = Enum.TextXAlignment.Left,
			TextSize = 30,
			Font = Enum.Font.Gotham,
			Size = UDim2.new(1, -20, 0, 60),
			Position = UDim2.new(0, 10, 0, y),
			Text = "    " .. label,
			Parent = sidebar,
		})
		Utils.ApplyCorner(button, Theme.Corner.Medium)
	end

	Utils.Create("TextLabel", {
		BackgroundTransparency = 1,
		Text = "Username\nPremium",
		TextColor3 = Theme.Colors.TextPrimary,
		TextSize = 28,
		Font = Enum.Font.Gotham,
		Size = UDim2.new(1, -20, 0, 100),
		Position = UDim2.new(0, 16, 1, -120),
		TextXAlignment = Enum.TextXAlignment.Left,
		TextYAlignment = Enum.TextYAlignment.Top,
		Parent = sidebar,
	})

	return sidebar
end

return Sidebar
end)()

__modules.topbar = (function()
	local Theme = __modules.theme
	local Utils = __modules.utils
local Topbar = {}

local function createIconButton(parent, emoji, x)
	local btn = Utils.Create("TextButton", {
		BackgroundColor3 = Theme.Colors.PanelSecondary,
		BorderSizePixel = 0,
		AutoButtonColor = false,
		Text = emoji,
		TextSize = 24,
		Font = Enum.Font.GothamBold,
		TextColor3 = Theme.Colors.TextPrimary,
		Size = UDim2.fromOffset(54, 54),
		Position = UDim2.new(1, x, 0, 0),
		Parent = parent,
	})
	Utils.ApplyCorner(btn, Theme.Corner.Medium)
	Utils.ApplyStroke(btn, Theme.Colors.Stroke, 0.4)
end

function Topbar.Create(parent, title)
	local frame = Utils.Create("Frame", {
		Name = "Topbar",
		BackgroundTransparency = 1,
		Size = UDim2.new(1, -40, 0, 84),
		Position = UDim2.fromOffset(20, 14),
		Parent = parent,
	})

	Utils.Create("TextLabel", {
		BackgroundTransparency = 1,
		Text = title,
		TextColor3 = Theme.Colors.TextPrimary,
		TextXAlignment = Enum.TextXAlignment.Left,
		Font = Enum.Font.GothamBold,
		TextSize = 40,
		Size = UDim2.new(0.45, 0, 1, 0),
		Parent = frame,
	})

	local search = Utils.Create("TextBox", {
		Name = "SearchBox",
		BackgroundColor3 = Theme.Colors.PanelSecondary,
		BorderSizePixel = 0,
		Text = "",
		PlaceholderText = "Search...",
		PlaceholderColor3 = Theme.Colors.TextSecondary,
		TextColor3 = Theme.Colors.TextPrimary,
		ClearTextOnFocus = false,
		TextSize = 28,
		Font = Enum.Font.Gotham,
		Size = UDim2.new(0, 500, 0, 54),
		Position = UDim2.new(0.5, -180, 0, 0),
		Parent = frame,
	})
	Utils.ApplyCorner(search, Theme.Corner.Medium)
	Utils.ApplyStroke(search, Theme.Colors.Stroke, 0.4)

	createIconButton(frame, "🔔", -180)
	createIconButton(frame, "⚙", -114)
	createIconButton(frame, "✕", -48)

	return frame
end

return Topbar
end)()

__modules.dashboard = (function()
	local Theme = __modules.theme
	local Utils = __modules.utils
local Dashboard = {}

local function createStatCard(parent, title, value, position)
	local card = Utils.Create("Frame", {
		BackgroundColor3 = Theme.Colors.PanelSecondary,
		BorderSizePixel = 0,
		Size = UDim2.new(0, 248, 0, 140),
		Position = position,
		Parent = parent,
	})
	Utils.ApplyCorner(card, Theme.Corner.Medium)
	Utils.ApplyStroke(card, Theme.Colors.Stroke, 0.5)

	Utils.Create("TextLabel", {
		BackgroundTransparency = 1,
		Text = title,
		TextColor3 = Theme.Colors.TextSecondary,
		TextSize = 24,
		Font = Enum.Font.Gotham,
		Size = UDim2.new(1, -20, 0, 34),
		Position = UDim2.new(0, 18, 0, 14),
		TextXAlignment = Enum.TextXAlignment.Left,
		Parent = card,
	})

	Utils.Create("TextLabel", {
		BackgroundTransparency = 1,
		Text = value,
		TextColor3 = Theme.Colors.TextPrimary,
		TextSize = 46,
		Font = Enum.Font.GothamBold,
		Size = UDim2.new(1, -20, 0, 58),
		Position = UDim2.new(0, 18, 0, 54),
		TextXAlignment = Enum.TextXAlignment.Left,
		Parent = card,
	})
end

local function createToggle(parent, label, enabled, y)
	Utils.Create("TextLabel", {
		BackgroundTransparency = 1,
		Text = label,
		TextColor3 = Theme.Colors.TextPrimary,
		TextSize = 20,
		Font = Enum.Font.Gotham,
		TextXAlignment = Enum.TextXAlignment.Left,
		Size = UDim2.new(1, -150, 0, 42),
		Position = UDim2.new(0, 22, 0, y),
		Parent = parent,
	})

	local toggle = Utils.Create("Frame", {
		BackgroundColor3 = enabled and Theme.Colors.Accent or Color3.fromRGB(55, 60, 72),
		BorderSizePixel = 0,
		Size = UDim2.fromOffset(82, 42),
		Position = UDim2.new(1, -104, 0, y),
		Parent = parent,
	})
	Utils.ApplyCorner(toggle, UDim.new(1, 0))
	local knob = Utils.Create("Frame", {
		BackgroundColor3 = Color3.new(1, 1, 1),
		BorderSizePixel = 0,
		Size = UDim2.fromOffset(32, 32),
		Position = enabled and UDim2.fromOffset(46, 5) or UDim2.fromOffset(5, 5),
		Parent = toggle,
	})
	Utils.ApplyCorner(knob, UDim.new(1, 0))
end

function Dashboard.Create(parent)
	local content = Utils.Create("Frame", {
		Name = "Content",
		BackgroundTransparency = 1,
		Size = UDim2.new(1, -320, 1, -140),
		Position = UDim2.new(0, 310, 0, 116),
		Parent = parent,
	})

	Utils.Create("TextLabel", {
		BackgroundTransparency = 1,
		Text = "Dashboard",
		TextColor3 = Theme.Colors.TextPrimary,
		TextSize = 56,
		Font = Enum.Font.GothamBold,
		Size = UDim2.new(1, 0, 0, 66),
		TextXAlignment = Enum.TextXAlignment.Left,
		Parent = content,
	})

	Utils.Create("TextLabel", {
		BackgroundTransparency = 1,
		Text = "Overview of your game stats.",
		TextColor3 = Theme.Colors.TextSecondary,
		TextSize = 30,
		Font = Enum.Font.Gotham,
		Size = UDim2.new(1, 0, 0, 40),
		Position = UDim2.fromOffset(0, 60),
		TextXAlignment = Enum.TextXAlignment.Left,
		Parent = content,
	})

	createStatCard(content, "Players", "12 / 16", UDim2.new(0, 0, 0, 112))
	createStatCard(content, "Ping", "42ms", UDim2.new(0, 266, 0, 112))
	createStatCard(content, "FPS", "144", UDim2.new(0, 532, 0, 112))
	createStatCard(content, "Region", "Singapore", UDim2.new(0, 798, 0, 112))

	local performance = Utils.Create("Frame", {
		BackgroundColor3 = Theme.Colors.PanelSecondary,
		BorderSizePixel = 0,
		Size = UDim2.new(0, 920, 0, 440),
		Position = UDim2.new(0, 0, 0, 270),
		Parent = content,
	})
	Utils.ApplyCorner(performance, Theme.Corner.Medium)
	Utils.ApplyStroke(performance, Theme.Colors.Stroke, 0.5)

	Utils.Create("TextLabel", {BackgroundTransparency = 1, Text = "Performance", TextColor3 = Theme.Colors.TextPrimary, TextSize = 48, Font = Enum.Font.GothamBold, Size = UDim2.new(1, -20, 0, 64), Position = UDim2.fromOffset(18, 14), TextXAlignment = Enum.TextXAlignment.Left, Parent = performance})
	Utils.Create("TextLabel", {BackgroundTransparency = 1, Text = "144 FPS", TextColor3 = Theme.Colors.Accent, TextSize = 44, Font = Enum.Font.GothamBold, Size = UDim2.new(0, 180, 0, 58), Position = UDim2.new(1, -190, 0, 22), TextXAlignment = Enum.TextXAlignment.Right, Parent = performance})

	local toggles = Utils.Create("Frame", {
		BackgroundColor3 = Theme.Colors.PanelSecondary,
		BorderSizePixel = 0,
		Size = UDim2.new(0, 430, 0, 440),
		Position = UDim2.new(0, 940, 0, 270),
		Parent = content,
	})
	Utils.ApplyCorner(toggles, Theme.Corner.Medium)
	Utils.ApplyStroke(toggles, Theme.Colors.Stroke, 0.5)

	Utils.Create("TextLabel", {BackgroundTransparency = 1, Text = "Quick Toggles", TextColor3 = Theme.Colors.TextPrimary, TextSize = 48, Font = Enum.Font.GothamBold, Size = UDim2.new(1, -20, 0, 64), Position = UDim2.fromOffset(18, 14), TextXAlignment = Enum.TextXAlignment.Left, Parent = toggles})
	createToggle(toggles, "Noclip", true, 94)
	createToggle(toggles, "Infinite Jump", true, 162)
	createToggle(toggles, "God Mode", true, 230)
	createToggle(toggles, "Fly", false, 298)
	createToggle(toggles, "Speed Boost", false, 366)

	return content
end

return Dashboard
end)()

return (function()
local Theme = __modules.theme
local Utils = __modules.utils
local Sidebar = __modules.sidebar
local Topbar = __modules.topbar
local Dashboard = __modules.dashboard

local Library = {}

function Library:CreateWindow(title)
	local guiParent = Utils.GetGuiParent()
	local oldGui = guiParent:FindFirstChild("WorstUiLibrary")
	if oldGui then
		oldGui:Destroy()
	end

	local screenGui = Utils.Create("ScreenGui", {Name = "WorstUiLibrary", ResetOnSpawn = false, IgnoreGuiInset = true, Parent = guiParent})

	local frame = Utils.Create("Frame", {
		Name = "Main",
		BackgroundColor3 = Theme.Colors.Background,
		BorderSizePixel = 0,
		AnchorPoint = Vector2.new(0.5, 0.5),
		Position = UDim2.fromScale(0.5, 0.5),
		Size = UDim2.fromOffset(1540, 930),
		Parent = screenGui,
	})
	Utils.ApplyCorner(frame, Theme.Corner.Large)
	Utils.ApplyStroke(frame, Theme.Colors.Stroke, 0.2)

	Topbar.Create(frame, title or "TitanUI Library")

	local body = Utils.Create("Frame", {
		BackgroundTransparency = 1,
		Size = UDim2.new(1, -20, 1, -115),
		Position = UDim2.new(0, 10, 0, 105),
		Parent = frame,
	})

	Sidebar.Create(body)
	Dashboard.Create(body)

	return screenGui
end

return Library
end)()
